### PR TITLE
Add requests to requirements

### PR DESCRIPTION
**Pull request by hillaryj**
Adds `requests` to the required modules and formats the line in setup.py prettier.

## 💭 Motivation and Context

Running the tool requires `requests` to be installed if it isn't already. 

## 🧪 Testing

Run `python setup.py install` like normal.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hillaryj** [comment]
Test output; looks like `docopt` has some deprecated functionality.
```
=============================================== test session starts ===============================================
platform darwin -- Python 3.7.7, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/bin/python
cachedir: .pytest_cache
rootdir: /Users/jeffreyh/GitHub/vpn-config-gen, inifile: pytest.ini
plugins: cov-2.8.1
collected 7 items

tests/test_vpnconf.py::test_stdout_version PASSED                                                           [ 14%]
tests/test_vpnconf.py::test_release_version SKIPPED                                                         [ 28%]
tests/test_vpnconf.py::test_log_levels[debug] PASSED                                                        [ 42%]
tests/test_vpnconf.py::test_log_levels[info] PASSED                                                         [ 57%]
tests/test_vpnconf.py::test_log_levels[warning] PASSED                                                      [ 71%]
tests/test_vpnconf.py::test_log_levels[error] PASSED                                                        [ 85%]
tests/test_vpnconf.py::test_log_levels[critical] PASSED                                                     [100%]

================================================ warnings summary =================================================
/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:165
/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:165
  /Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:165: DeprecationWarning: invalid escape sequence \S

/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:166
/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:166
  /Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:166: DeprecationWarning: invalid escape sequence \[

/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:207
/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:207
  /Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:207: DeprecationWarning: invalid escape sequence \[

/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:456
/Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:456
  /Users/jeffreyh/.pyenv/versions/3.7.7/envs/vpn-config-gen/lib/python3.7/site-packages/docopt-0.6.2-py3.7.egg/docopt.py:456: DeprecationWarning: invalid escape sequence \S

-- Docs: https://docs.pytest.org/en/latest/warnings.html

---------- coverage: platform darwin, python 3.7.7-final-0 -----------
Name                      Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------------------------
src/vpnconf/__init__.py       3      0      0      0   100%
src/vpnconf/_version.py       1      0      0      0   100%
src/vpnconf/vpnconf.py       72     10     28      6    82%   43, 78, 83, 92-94, 116-119, 140, 42->43, 68->64, 77->78, 82->83, 85->87, 139->140
---------------------------------------------------------------------
TOTAL                        76     10     28      6    83%

============================================= short test summary info =============================================
SKIPPED [1] tests/test_vpnconf.py:40: this is not a release (RELEASE_TAG not set)
==================================== 6 passed, 1 skipped, 8 warnings in 4.45s =====================================
```

**Review by felddy — APPROVED** [review]
Good catch.  My pyenv must not have been as air-tight as I had hoped.  🥬

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by jsf9k — CHANGES_REQUESTED** [review]
The change itself is good, but the [Coveralls](https://coveralls.io) foo is broken because GitHub Actions does not integrate as tightly with that site as TravisCI did.  We need to provide a token.

@hillaryj or @felddy, can you fix this?  Failing that, we should remove the coveralls jazz.

**Comment by hillaryj** [comment]
Maybe @felddy can - @mcdonnnj and I worked on it earlier and even after adding the token into my repo the coveralls foo still is broken.

**Comment by hillaryj** [comment]
Another option would be to make it so I can push branches to the repo and I can move from a fork to a branch instead. This repo isn't in the list of ones that I got privileges for when joining the org and team.

**Comment by jsf9k** [comment]
> Another option would be to make it so I can push branches to the repo and I can move from a fork to a branch instead. This repo isn't in the list of ones that I got privileges for when joining the org and team.

You should have direct access now.  The problem was that the repo itself hadn't given admin rights to @cisagov/team-ois.  As a member of @cisagov/team-ois you should have access to all of our team's repos in this organization.

**Comment by hillaryj** [comment]
Closing; replaced by https://github.com/cisagov/vpn-config-gen/pull/2

**Pull request closed without merging**
